<<<<<<< HEAD
version: '3.8'

=======
>>>>>>> 61035f8aec56fdf935f8ae0bb4243ef378b043d8
services:
  backend:
    build:
      context: ./teachua-backend-NatVor
      dockerfile: Dockerfile
    container_name: teachua-backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    entrypoint: ["sh", "-c", "sleep 30 && java -jar /app/dev.war"]
    env_file:
      - .env
    environment:
      JDBC_DRIVER: ${JDBC_DRIVER}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USER: ${DATASOURCE_USER}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      HIBERNATE_SHOW_SQL: true
      HIBERNATE_HBM2DDL_AUTO: update
    restart: always

  frontend:
    build:
      context: ./teachua-frontend-NatVor
      dockerfile: Dockerfile
    container_name: teachua-frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_ROOT_SERVER: "http://teachua-backend:8080"
    restart: always
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
<<<<<<< HEAD
      - ./teachua-frontend-NatVor/nginx.conf:/etc/nginx/nginx.conf
=======
      - nginx.conf:/etc/nginx/nginx.conf
>>>>>>> 61035f8aec56fdf935f8ae0bb4243ef378b043d8
    depends_on:
      - backend
    restart: always
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teachua
      MYSQL_USER: ${DATASOURCE_USER}
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    command: >
      --character-set-server=utf8
      --collation-server=utf8_bin
    restart: always

volumes:
  mariadb_data:
