name: Deploy Application to AKS

on:
   push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group rg-rare-elf --name cluster-golden-cardinal

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./kubernetes/
          sleep 40
          kubectl get service -o wide

      - name: Clean Up Kube Config
        run: rm -rf ~/.kube
