name: Deploy Application to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group rg-rare-elf --name cluster-golden-cardinal

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./kubernetes/
          sleep 40
          kubectl get service -o wide

      - name: Test Application Availability
        run: |
          sleep 60
          backend_ip=$(kubectl get service teachua-backend-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          frontend_ip=$(kubectl get service teachua-frontend-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Backend Service IP: $backend_ip"
          echo "Frontend Service IP: $frontend_ip"
          # curl -sSf http://$backend_ip
          # curl -sSf http://$frontend_ip

      - name: AKS Monitoring Enabler
        run: |
          az aks get-credentials -n "cluster-golden-cardinal" -g "rg-rare-elf"
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

          # Assuming you have existing releases named 'prometheus' and 'grafana'
          helm upgrade prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --reuse-values
          helm upgrade grafana grafana/grafana --namespace monitoring --reuse-values --set adminPassword='YOUR_ADMIN_PASSWORD'

          kubectl get svc -n monitoring > monitoring_services.txt
          rm -rf ~/.kube

      - name: Upload Monitoring Services Result
        uses: actions/upload-artifact@v3
        with:
          name: monitoring-services
          path: monitoring_services.txt
      #- name: Run SonarQube Inspection
      # uses: sonarsource/sonarqube-scan-action@v1.0.0
      # env:
      #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # with:
      #   args: >
      #     -Dsonar.projectKey=myproject
      #     -Dsonar.host.url=http://localhost:9000
      #     -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  integration_tests:
    runs-on: ubuntu-latest
    needs: [Deploy-Application]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Set execute permissions for integration test script
        run: chmod +x ./integration-test.sh

      - name: Run integration tests
        run: ./integration-test.sh
