name: Backend CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Build with Maven
        run: mvn clean package

      - name: Run unit tests
        run: mvn test

  database_integration:
    name: Database Integration Test
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: teachua_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run integration tests
        env:
          DATASOURCE_URL: jdbc:mysql://localhost:3306/teachua_test?useUnicode=true&serverTimezone=UTC
          DATASOURCE_USER: root
          DATASOURCE_PASSWORD: root
        run: mvn integration-test

  
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/devops-projectlevel/teachua-backend-natvor/teachua-backend:new .
