name: Backend CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to build the backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t teachua-backend ./teachua-backend-NatVor
          docker run --rm teachua-backend mvn clean package

      # Step to build the frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t teachua-frontend ./teachua-frontend-NatVor

      # Step to run unit tests
      - name: Run unit tests
        run: |
          docker run --rm teachua-backend mvn test

      # Step to run integration tests
      - name: Run integration tests
        run: |
          docker run --rm \
            -e DATASOURCE_URL=jdbc:mysql://mysql:3306/teachua_test?useUnicode=true&serverTimezone=UTC \
            -e DATASOURCE_USER=root \
            -e DATASOURCE_PASSWORD=root \
            teachua-backend mvn integration-test

      # Step to login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step to push backend Docker image to GitHub Container Registry
      - name: Push Backend Docker image to GitHub Container Registry
        run: docker tag teachua-backend:latest ghcr.io/${{ github.repository }}/teachua-backend:latest && docker push ghcr.io/${{ github.repository }}/teachua-backend:latest

      # Step to push frontend Docker image to GitHub Container Registry
      - name: Push Frontend Docker image to GitHub Container Registry
        run: docker tag teachua-frontend:latest ghcr.io/${{ github.repository }}/teachua-frontend:latest && docker push ghcr.io/${{ github.repository }}/teachua-frontend:latest

      # Step to deploy using docker-compose
      - name: Deploy using docker-compose
        run: docker-compose -f docker-compose.ci.yml up -d

# Example docker-compose.ci.yml
# This file should be placed in the root of your repository

services:
  backend:
    image: ghcr.io/${{ github.repository }}/teachua-backend:latest
    container_name: teachua-backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    entrypoint: ["sh", "-c", "sleep 30 && java -jar /app/dev.war"]
    env_file:
      - .env
    environment:
      JDBC_DRIVER: ${JDBC_DRIVER}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_U
