name: Backend CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Build with Maven
        run: mvn clean package

      - name: Run unit tests
        run: mvn test

  database_integration:
    name: Database Integration Test
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: teachua_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run integration tests
        env:
          DATASOURCE_URL: jdbc:mysql://localhost:3306/teachua_test?useUnicode=true&serverTimezone=UTC
          DATASOURCE_USER: root
          DATASOURCE_PASSWORD: root
        run: mvn integration-test

  code_inspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SonarQube Scanner
        run: |
          sudo apt-get install -y unzip
          curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip -o /tmp/sonar-scanner-cli.zip -d /tmp
          sudo mv /tmp/sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Configure SonarQube
        env:
          SONAR_SCANNER_VERSION: 4.6.2.2472
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=teachua-backend \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/devops-projectlevel/teachua-backend-natvor/teachua-backend:new .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/devops-projectlevel/teachua-backend-natvor/teachua-backend:new
